Repository mszostok/version, pull requests merged in 2023-05, with the labels that each got.

#96 Bump all dependencies reported by Dependabot
  .github/workflows/coverall.yml
  .github/workflows/testing.yml
  examples/go.mod
  examples/go.sum
  go.mod
  go.sum
  magefiles/go.mod
  magefiles/go.sum
  tests/go.mod
  tests/go.sum
Labels: dependencies

#103 Bump all dependencies, add target to refresh all go mods
  .github/workflows/coverall.yml
  .github/workflows/testing.yml
  examples/go.mod
  examples/go.sum
  go.mod
  go.sum
  magefiles/go.mod
  magefiles/go.sum
  magefiles/magefile.go
Labels: dependencies

#92 Add option to load config from file
  printer/opts.go
  printer/pretty.go
  printer/printer_test.go
  printer/testdata/TestPrinterStyleFileOptions/Print_custom_layout.golden.txt
  printer/testdata/TestPrinterStyleFileOptions/Print_default_layout.golden.txt
  printer/testdata/TestPrinterStyleFileOptions/customStyle.json
  printer/testdata/TestPrinterStyleFileOptions/customStyle.yaml
  printer/testdata/TestPrinterStyleFileOptions/invalidStyle.json
  printer/testdata/TestPrinterStyleFileOptions/invalidStyle.yaml
  printer/testdata/TestPrinterStyleFromEnvOptionsUseDefaults.golden.txt
Labels: enhancement, area/customization

#104 Update docs, port bash script to Go, add example
  docs/assets/examples/screen-custom-layout--env-style.png
  docs/customization/pretty/format.md
  docs/customization/pretty/layout.md
  docs/examples.md
  examples/custom-layout/main.go
  examples/style.yaml
  magefiles/hack/gallery.sh
  magefiles/magefile.go
  magefiles/target/gallery.go
  printer/opts.go
  style/config.go
Labels: enhancement
